name: Kernel Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y bc bison flex libssl-dev libelf-dev build-essential clang lld

      - name: Build the kernel
        run: |
          echo "Building the kernel..."
          make O=out ARCH=arm64 CC=clang zumapro_defconfig
          make O=out ARCH=arm64 CC=clang -j$(nproc)

      - name: Upload kernel image
        uses: actions/upload-artifact@v4
        with:
          name: Image.gz
          path: out/arch/arm64/boot/Image.gz
